version: '3'
services:
  react-app:
    image: todo-front
    ports:
      - '3000:3000'
  api-server:
    image: todo-back
    ports:
      - '3001:3001'
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
